// ─── Canonical Action Event Rules ───────────────────────────────────

import type { CanonicalActionType } from './types';

export type DomainEventType =
  | 'ENTITY_MOVED'
  | 'ZONE_CHANGED'
  | 'ENTITY_CREATED'
  | 'ENTITY_DESTROYED'
  | 'PROPERTY_SET'
  | 'CONTROL_TRANSFERRED'
  | 'ENTITY_DRAWN'
  | 'ZONE_SHUFFLED'
  | 'ENTITY_REVEALED'
  | 'ENTITY_HIDDEN'
  | 'DECISION_REQUESTED'
  | 'DECISION_MADE'
  | 'PRIORITY_PASSED'
  | 'STEP_ADVANCED'
  | 'PHASE_ADVANCED'
  | 'TURN_ENDED'
  | 'TURN_STARTED'
  | 'STACK_ITEM_QUEUED'
  | 'STACK_ITEM_RESOLVED'
  | 'RESOURCE_CHANGED'
  | 'SCORE_SET'
  | 'PLAYER_ELIMINATED'
  | 'GAME_ENDED'
  | 'EXTRA_TURN_ADDED'
  | 'TURN_SKIPPED'
  | 'TURN_ORDER_REVERSED'
  | 'PHASE_INSERTED'
  | 'STEP_INSERTED';

export const canonicalActionEventMap: Record<CanonicalActionType, DomainEventType[]> = {
  MOVE_ENTITY: ['ENTITY_MOVED', 'ZONE_CHANGED'],
  CREATE_ENTITY: ['ENTITY_CREATED', 'ZONE_CHANGED'],
  DESTROY_ENTITY: ['ENTITY_DESTROYED', 'ZONE_CHANGED'],
  SET_PROPERTY: ['PROPERTY_SET'],
  TRANSFER_CONTROL: ['CONTROL_TRANSFERRED'],
  DRAW_FROM_ZONE: ['ENTITY_DRAWN', 'ZONE_CHANGED'],
  SHUFFLE_ZONE: ['ZONE_SHUFFLED'],
  REVEAL_ENTITY: ['ENTITY_REVEALED'],
  HIDE_ENTITY: ['ENTITY_HIDDEN'],
  PROMPT_PLAYER: ['DECISION_REQUESTED'],
  CHOOSE_OPTION: ['DECISION_MADE'],
  PASS_PRIORITY: ['PRIORITY_PASSED'],
  ADVANCE_STEP: ['STEP_ADVANCED'],
  ADVANCE_PHASE: ['PHASE_ADVANCED'],
  END_TURN: ['TURN_ENDED', 'TURN_STARTED'],
  QUEUE_STACK_ITEM: ['STACK_ITEM_QUEUED'],
  RESOLVE_STACK_ITEM: ['STACK_ITEM_RESOLVED'],
  ADD_RESOURCE: ['RESOURCE_CHANGED'],
  REMOVE_RESOURCE: ['RESOURCE_CHANGED'],
  SET_SCORE: ['SCORE_SET'],
  ELIMINATE_PLAYER: ['PLAYER_ELIMINATED'],
  END_GAME: ['GAME_ENDED'],
  ADD_EXTRA_TURN: ['EXTRA_TURN_ADDED'],
  SKIP_TURN: ['TURN_SKIPPED'],
  REVERSE_TURN_ORDER: ['TURN_ORDER_REVERSED'],
  INSERT_PHASE: ['PHASE_INSERTED'],
  INSERT_STEP: ['STEP_INSERTED'],
};

export function getEventsForCanonicalAction(
  actionType: CanonicalActionType,
): DomainEventType[] {
  return canonicalActionEventMap[actionType];
}
