import type { RawEntry } from './types';

export const BOARDS: RawEntry[] = [
  // ----- Game boards (category: boards) -----
  {
    group: 'board',
    identity: 'Board (Accordion)',
    displayName: 'Accordion Board Set',
    widthIn: 8,
    heightIn: 16,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 10.5 },
      { minCopies: 100, perSheet: 7.05 },
    ],
    confidence: 'high',
    notes: 'Boards priced per sheet; optional UV/Linen +$0.25/sheet each.',
  },
  {
    group: 'board',
    identity: 'Board (Bi-Fold)',
    displayName: 'Bi-Fold Game Board',
    widthIn: 9,
    heightIn: 18,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 8.5 },
      { minCopies: 100, perSheet: 6.24 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Quad-Fold)',
    displayName: 'Quad-Fold Game Board',
    widthIn: 18,
    heightIn: 18,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 11.89 },
      { minCopies: 100, perSheet: 8.7 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Large Quad-Fold)',
    displayName: 'Large Quad-Fold Game Board',
    widthIn: 20,
    heightIn: 20,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 14.73 },
      { minCopies: 100, perSheet: 10.87 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Six-Fold)',
    displayName: 'Six-Fold Game Board',
    widthIn: 27,
    heightIn: 18,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 20.3 },
      { minCopies: 100, perSheet: 16.3 },
    ],
    confidence: 'high',
    notes: 'Largest fold board.',
  },
  {
    group: 'board',
    identity: 'Board (Medium Six-Fold)',
    displayName: 'Medium Six-Fold Game Board',
    widthIn: 16,
    heightIn: 16,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 12.8 },
      { minCopies: 100, perSheet: 9.45 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Large Square)',
    displayName: 'Large Square Board Set',
    widthIn: 10,
    heightIn: 10,
    thicknessIn: 0.07,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 10.0 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Square)',
    displayName: 'Square Board Set',
    widthIn: 8,
    heightIn: 8,
    thicknessIn: 0.07,
    itemsPerSheet: 2,
    priceTiers: [
      { minCopies: 1, perItem: 5.33, perSheet: 10.67 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
    notes: '2 per sheet.',
  },
  {
    group: 'board',
    identity: 'Board (Small Square)',
    displayName: 'Small Square Board Set',
    widthIn: 4,
    heightIn: 4,
    thicknessIn: 0.07,
    itemsPerSheet: 8,
    priceTiers: [
      { minCopies: 1, perItem: 1.48, perSheet: 11.8 },
      { minCopies: 100, perItem: 0.76, perSheet: 6.1 },
    ],
    confidence: 'high',
    notes: '8 per sheet.',
  },
  {
    group: 'board',
    identity: 'Board (Half)',
    displayName: 'Half Board Set',
    widthIn: 5,
    heightIn: 10,
    thicknessIn: 0.07,
    itemsPerSheet: 3,
    priceTiers: [
      { minCopies: 1, perItem: 3.67, perSheet: 11.0 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Quarter)',
    displayName: 'Quarter Board Set',
    widthIn: 5,
    heightIn: 5,
    thicknessIn: 0.07,
    itemsPerSheet: 6,
    priceTiers: [
      { minCopies: 1, perItem: 1.67, perSheet: 10.0 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Domino)',
    displayName: 'Domino Board Set',
    widthIn: 4,
    heightIn: 8,
    thicknessIn: 0.07,
    itemsPerSheet: 4,
    priceTiers: [
      { minCopies: 1, perItem: 2.75, perSheet: 11.0 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Skinny)',
    displayName: 'Skinny Board Set',
    widthIn: 4,
    heightIn: 10,
    thicknessIn: 0.07,
    itemsPerSheet: 4,
    priceTiers: [
      { minCopies: 1, perItem: 2.85, perSheet: 11.4 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Strip)',
    displayName: 'Strip Board Set',
    widthIn: 2,
    heightIn: 10,
    thicknessIn: 0.07,
    itemsPerSheet: 7,
    priceTiers: [
      { minCopies: 1, perItem: 1.75, perSheet: 12.25 },
      { minCopies: 100, perSheet: 5.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Sliver)',
    displayName: 'Sliver Board Set',
    widthIn: 2,
    heightIn: 8,
    thicknessIn: 0.07,
    itemsPerSheet: 10,
    priceTiers: [
      { minCopies: 1, perItem: 1.27, perSheet: 12.75 },
      { minCopies: 100, perItem: 0.61, perSheet: 6.1 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Dual Layer Large)',
    displayName: 'Large Dual Layer Board Set',
    widthIn: 8,
    heightIn: 10,
    thicknessIn: 0.14,
    itemsPerSheet: 1,
    priceTiers: [
      { minCopies: 1, perSheet: 9.1 },
      { minCopies: 100, perSheet: 4.97 },
    ],
    confidence: 'high',
    notes: '4mm thick, 1 printed side.',
  },
  {
    group: 'board',
    identity: 'Board (Dual Layer Medium)',
    displayName: 'Medium Dual Layer Board Set',
    widthIn: 8,
    heightIn: 4,
    thicknessIn: 0.14,
    itemsPerSheet: 2,
    priceTiers: [
      { minCopies: 1, perSheet: 8.76 },
      { minCopies: 100, perSheet: 4.63 },
    ],
    confidence: 'high',
  },
  {
    group: 'board',
    identity: 'Board (Dual Layer Small)',
    displayName: 'Small Dual Layer Board Set',
    widthIn: 3.5,
    heightIn: 5.5,
    thicknessIn: 0.14,
    itemsPerSheet: 4,
    priceTiers: [
      { minCopies: 1, perSheet: 8.51 },
      { minCopies: 100, perSheet: 4.38 },
    ],
    confidence: 'high',
  },
];
