import type { RawEntry } from './types';

export const BOOKLETS: RawEntry[] = [
  // ----- Booklets / books / documents (category: booklets) -----
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Small Booklet',
    widthIn: 2.5,
    heightIn: 3.5,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 2.75 },
      { minCopies: 100, costEach: 2.01 },
    ],
    confidence: 'high',
    notes: 'Saddle-stitched; example 4 pages.',
  },
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Medium Booklet',
    widthIn: 3.5,
    heightIn: 5,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 2.75 },
      { minCopies: 100, costEach: 2.01 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Large Booklet',
    widthIn: 5,
    heightIn: 8,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 1.88 },
      { minCopies: 100, costEach: 1.38 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Tall Booklet',
    widthIn: 4.5,
    heightIn: 8,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 2.31 },
      { minCopies: 100, costEach: 1.72 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Jumbo Booklet',
    widthIn: 8,
    heightIn: 10,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 2.06 },
      { minCopies: 100, costEach: 1.5 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'Booklet',
    displayName: 'Tarot Booklet',
    widthIn: 2.75,
    heightIn: 4.75,
    maxPages: 40,
    priceTiers: [
      { minCopies: 1, costEach: 2.75 },
      { minCopies: 100, costEach: 2.01 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'PerfectBoundBook',
    displayName: 'Digest Perfect Bound Book',
    widthIn: 5.38,
    heightIn: 8.39,
    maxPages: 200,
    priceTiers: [
      { minCopies: 1, costEach: 11.45 },
      { minCopies: 100, costEach: 8.64 },
    ],
    confidence: 'high',
    notes: 'Example 40 pages.',
  },
  {
    group: 'booklet',
    identity: 'PerfectBoundBook',
    displayName: 'Letter Perfect Bound Book',
    widthIn: 8.51,
    heightIn: 11,
    maxPages: 200,
    priceTiers: [
      { minCopies: 1, costEach: 12.1 },
      { minCopies: 100, costEach: 9.0 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'CoilBook',
    displayName: 'Medium Coil Book',
    widthIn: 5.61,
    heightIn: 7.5,
    maxPages: 200,
    priceTiers: [
      { minCopies: 1, costEach: 7.65 },
      { minCopies: 100, costEach: 5.69 },
    ],
    confidence: 'high',
    notes: 'Spiral/coil bound.',
  },
  {
    group: 'booklet',
    identity: 'CoilBook',
    displayName: 'Jumbo Coil Book',
    widthIn: 9.36,
    heightIn: 10,
    maxPages: 200,
    priceTiers: [
      { minCopies: 1, costEach: 7.34 },
      { minCopies: 100, costEach: 5.37 },
    ],
    confidence: 'high',
  },
  {
    group: 'booklet',
    identity: 'MatBook',
    displayName: 'Medium Mat Book',
    widthIn: 5.61,
    heightIn: 7.5,
    maxPages: 100,
    priceTiers: [
      { minCopies: 1, costEach: 8.18 },
      { minCopies: 100, costEach: 6.02 },
    ],
    confidence: 'medium',
    notes: 'Identity inferred.',
  },
  {
    group: 'booklet',
    identity: 'Document',
    displayName: 'Document (Loose Sheets)',
    widthIn: 8.5,
    heightIn: 11,
    maxPages: 1000,
    priceTiers: [
      { minCopies: 1, costEach: 1.82 },
      { minCopies: 100, costEach: 1.33 },
    ],
    confidence: 'high',
    notes: 'Loose printed sheets, up to 1000 pages.',
  },
  {
    group: 'booklet',
    identity: 'Folio',
    displayName: 'Poker Folio Set',
    widthIn: 10,
    heightIn: 3.5,
    priceTiers: [
      { minCopies: 1, costEach: 2.6 },
      { minCopies: 100, costEach: 1.32 },
    ],
    confidence: 'high',
    notes: 'Folded rules folio; identity inferred.',
  },
];
