import type { RawEntry } from './types';

export const BOXES: RawEntry[] = [
  // ----- Boxes & packaging (category: boxes) -----
  {
    group: 'box',
    identity: 'HookBox',
    displayName: 'Poker Hook Box',
    widthIn: 2.5,
    heightIn: 3.5,
    cardCapacityOptions: [18, 36, 54, 72, 90, 108],
    priceTiers: [
      { minCopies: 1, costEach: 3.28 },
      { minCopies: 100, costEach: 1.4 },
    ],
    confidence: 'high',
    notes: 'Same price all capacities; depth varies.',
  },
  {
    group: 'box',
    identity: 'HookBox',
    displayName: 'Bridge Hook Box',
    widthIn: 2.25,
    heightIn: 3.5,
    cardCapacityOptions: [54, 108],
    priceTiers: [
      { minCopies: 1, costEach: 3.28 },
      { minCopies: 100, costEach: 1.4 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'HookBox',
    displayName: 'Jumbo Hook Box',
    widthIn: 3.5,
    heightIn: 5.5,
    cardCapacityOptions: [36, 90],
    priceTiers: [
      { minCopies: 1, costEach: 3.28 },
      { minCopies: 100, costEach: 1.4 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'HookBox',
    displayName: 'Tarot Hook Box',
    widthIn: 2.75,
    heightIn: 4.75,
    cardCapacityOptions: [40, 90],
    priceTiers: [
      { minCopies: 1, costEach: 3.28 },
      { minCopies: 100, costEach: 1.4 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'HookBox',
    displayName: 'Square Hook Box',
    widthIn: 3.5,
    heightIn: 3.75,
    cardCapacityOptions: [48, 96],
    priceTiers: [
      { minCopies: 1, costEach: 3.28 },
      { minCopies: 100, costEach: 1.4 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'TuckBox',
    displayName: 'Poker Tuck Box',
    widthIn: 2.5,
    heightIn: 3.5,
    cardCapacityOptions: [36, 54, 72, 90, 108],
    priceTiers: [
      { minCopies: 1, costEach: 5.85 },
      { minCopies: 100, costEach: 3.65 },
    ],
    confidence: 'high',
    notes: 'Same price all capacities; depth varies.',
  },
  {
    group: 'box',
    identity: 'TuckBox',
    displayName: 'Bridge Tuck Box',
    widthIn: 2.25,
    heightIn: 3.5,
    cardCapacityOptions: [54, 108],
    priceTiers: [
      { minCopies: 1, costEach: 5.85 },
      { minCopies: 100, costEach: 3.65 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'TuckBox',
    displayName: 'Jumbo Tuck Box',
    widthIn: 3.5,
    heightIn: 5.5,
    cardCapacityOptions: [90],
    priceTiers: [
      { minCopies: 1, costEach: 5.85 },
      { minCopies: 100, costEach: 3.65 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'TuckBox',
    displayName: 'Tarot Tuck Box',
    widthIn: 2.75,
    heightIn: 4.75,
    cardCapacityOptions: [40, 90],
    priceTiers: [
      { minCopies: 1, costEach: 5.85 },
      { minCopies: 100, costEach: 3.65 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'TuckBox',
    displayName: 'Square Tuck Box',
    widthIn: 3.5,
    heightIn: 3.75,
    cardCapacityOptions: [48, 96],
    priceTiers: [
      { minCopies: 1, costEach: 5.85 },
      { minCopies: 100, costEach: 3.65 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'MintTin',
    displayName: 'Mint Tin',
    widthIn: 2.13,
    heightIn: 3.55,
    depthIn: 0.83,
    priceTiers: [
      { minCopies: 1, costEach: 5.02 },
      { minCopies: 100, costEach: 3.72 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'MintTin',
    displayName: 'Tall Mint Tin',
    widthIn: 2.2,
    heightIn: 3.6,
    depthIn: 1.25,
    priceTiers: [
      { minCopies: 1, costEach: 5.02 },
      { minCopies: 100, costEach: 3.72 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'StoutBox',
    displayName: 'Small Stout Box',
    widthIn: 3.6,
    heightIn: 5.5,
    depthIn: 2.0,
    priceTiers: [
      { minCopies: 1, costEach: 13.0 },
      { minCopies: 100, costEach: 9.5 },
    ],
    confidence: 'high',
    notes: 'Telescoping 2-piece box.',
  },
  {
    group: 'box',
    identity: 'StoutBox',
    displayName: 'Medium Stout Box',
    widthIn: 5.63,
    heightIn: 8.59,
    depthIn: 2.0,
    priceTiers: [
      { minCopies: 1, costEach: 15.5 },
      { minCopies: 100, costEach: 11.4 },
    ],
    confidence: 'high',
    notes: 'Full box printed.',
  },
  {
    group: 'box',
    identity: 'StoutBox',
    displayName: 'Large Stout Box',
    widthIn: 10.75,
    heightIn: 10.75,
    depthIn: 3.0,
    priceTiers: [
      { minCopies: 1, costEach: 28.0 },
      { minCopies: 100, costEach: 25.0 },
    ],
    confidence: 'high',
    notes: 'Full box printed.',
  },
  {
    group: 'box',
    identity: 'ProBox',
    displayName: 'Small Pro Box',
    widthIn: 5.5,
    heightIn: 3.5,
    depthIn: 1.0,
    priceTiers: [
      { minCopies: 1, costEach: 9.09 },
      { minCopies: 100, costEach: 6.42 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'ProBox',
    displayName: 'Medium Pro Box',
    widthIn: 8.2,
    heightIn: 4.7,
    depthIn: 1.4,
    priceTiers: [
      { minCopies: 1, costEach: 11.25 },
      { minCopies: 100, costEach: 7.7 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'PrototypeBox',
    displayName: 'Small Prototype Box',
    widthIn: 4.75,
    heightIn: 3.63,
    depthIn: 2.13,
    priceTiers: [
      { minCopies: 1, costEach: 5.7 },
      { minCopies: 100, costEach: 4.69 },
    ],
    confidence: 'high',
    notes: 'Plain prototype box.',
  },
  {
    group: 'box',
    identity: 'RetailBox',
    displayName: 'Large Retail Box',
    widthIn: 11.63,
    heightIn: 9.13,
    depthIn: 2.0,
    priceTiers: [
      { minCopies: 1, costEach: 14.4 },
      { minCopies: 100, costEach: 9.5 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'DeckBox',
    displayName: 'Deck Box',
    widthIn: 3.77,
    heightIn: 7.9,
    depthIn: 3.03,
    priceTiers: [
      { minCopies: 1, costEach: 15.75 },
      { minCopies: 100, costEach: 10.75 },
    ],
    confidence: 'high',
    notes: 'Full box printed.',
  },
  {
    group: 'box',
    identity: 'BoosterBox',
    displayName: 'Poker Booster Box',
    widthIn: 5.18,
    heightIn: 5.75,
    depthIn: 2.35,
    priceTiers: [
      { minCopies: 1, costEach: 9.65 },
      { minCopies: 100, costEach: 5.9 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'BoosterPack',
    displayName: 'Poker Booster Pack',
    widthIn: 2.5,
    heightIn: 3.5,
    depthIn: 0.23,
    priceTiers: [
      { minCopies: 1, costEach: 2.76 },
      { minCopies: 100, costEach: 0.95 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'Envelope',
    displayName: 'Poker Envelope',
    widthIn: 2.85,
    heightIn: 4.4,
    depthIn: 0.23,
    priceTiers: [
      { minCopies: 1, costEach: 1.73 },
      { minCopies: 100, costEach: 1.05 },
    ],
    confidence: 'high',
  },
  {
    group: 'box',
    identity: 'VHSBox',
    displayName: 'VHS Box',
    widthIn: 7.4,
    heightIn: 4.5,
    depthIn: 0.9,
    priceTiers: [
      { minCopies: 1, costEach: 4.57 },
      { minCopies: 100, costEach: 2.25 },
    ],
    confidence: 'high',
  },
];
