import type { RawEntry } from './types';

export const DECKS: RawEntry[] = [
  // ----- Card decks (category: cards) -----
  {
    group: 'deck',
    identity: 'PokerDeck',
    displayName: 'Poker Deck',
    widthIn: 2.5,
    heightIn: 3.5,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 2.99 },
      { minCopies: 100, perSheet18: 1.69 },
    ],
    confidence: 'high',
    notes: 'Standard US poker size.',
  },
  {
    group: 'deck',
    identity: 'EuroPokerDeck',
    displayName: 'Euro Poker Deck',
    widthIn: 2.48,
    heightIn: 3.46,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 3.09 },
      { minCopies: 100, perSheet18: 1.78 },
    ],
    confidence: 'high',
    notes: 'European 63x88mm poker size.',
  },
  {
    group: 'deck',
    identity: 'BridgeDeck',
    displayName: 'Bridge Deck',
    widthIn: 2.25,
    heightIn: 3.5,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 3.09 },
      { minCopies: 100, perSheet18: 1.78 },
    ],
    confidence: 'high',
    notes: 'Narrow bridge size.',
  },
  {
    group: 'deck',
    identity: 'MiniDeck',
    displayName: 'Mini Deck',
    widthIn: 1.75,
    heightIn: 2.5,
    cardsPerSheet: 32,
    priceTiers: [
      { minCopies: 1, perSheet32: 3.85 },
      { minCopies: 100, perSheet32: 2.2 },
    ],
    confidence: 'high',
    notes: 'Single Mini product (no Mini-American/European split).',
  },
  {
    group: 'deck',
    identity: 'TarotDeck',
    displayName: 'Tarot Deck',
    widthIn: 2.75,
    heightIn: 4.75,
    cardsPerSheet: 10,
    priceTiers: [
      { minCopies: 1, perSheet10: 2.84 },
      { minCopies: 100, perSheet10: 1.55 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'FoilTarotDeck',
    displayName: 'Foil Tarot Deck',
    widthIn: 2.75,
    heightIn: 4.75,
    cardsPerSheet: 10,
    priceTiers: [
      { minCopies: 1, perSheet10: 7.47 },
      { minCopies: 100, perSheet10: 3.43 },
    ],
    confidence: 'high',
    notes: 'Foil-stamped tarot.',
  },
  {
    group: 'deck',
    identity: 'FoilPokerDeck',
    displayName: 'Foil Poker Deck',
    widthIn: 2.5,
    heightIn: 3.5,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 6.19 },
      { minCopies: 100, perSheet18: 3.13 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'FoilPokerDeck',
    displayName: 'Foil Euro Poker Deck',
    widthIn: 2.48,
    heightIn: 3.46,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 6.39 },
      { minCopies: 100, perSheet18: 3.33 },
    ],
    confidence: 'medium',
    notes: 'Euro variant of foil poker; identity may take a size param.',
  },
  {
    group: 'deck',
    identity: 'JumboDeck',
    displayName: 'Jumbo Deck',
    widthIn: 3.5,
    heightIn: 5.5,
    cardsPerSheet: 6,
    priceTiers: [
      { minCopies: 1, perSheet6: 2.7 },
      { minCopies: 100, perSheet6: 1.43 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'SquareDeck',
    displayName: 'Square Deck',
    widthIn: 3.5,
    heightIn: 3.5,
    cardsPerSheet: 12,
    priceTiers: [
      { minCopies: 1, perSheet12: 3.0 },
      { minCopies: 100, perSheet12: 1.62 },
    ],
    confidence: 'high',
    notes: 'Large square (3.5in).',
  },
  {
    group: 'deck',
    identity: 'EuroSquareDeck',
    displayName: 'Euro Square Deck',
    widthIn: 2.76,
    heightIn: 2.76,
    cardsPerSheet: 15,
    priceTiers: [
      { minCopies: 1, perSheet15: 3.55 },
      { minCopies: 100, perSheet15: 1.7 },
    ],
    confidence: 'high',
    notes: '70mm square.',
  },
  {
    group: 'deck',
    identity: 'SmallSquareDeck',
    displayName: 'Small Square Deck',
    widthIn: 2.5,
    heightIn: 2.5,
    cardsPerSheet: 24,
    priceTiers: [
      { minCopies: 1, perSheet24: 3.55 },
      { minCopies: 100, perSheet24: 1.98 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'MicroDeck',
    displayName: 'Micro Deck',
    widthIn: 1.25,
    heightIn: 1.75,
    cardsPerSheet: 36,
    priceTiers: [
      { minCopies: 1, perSheet36: 3.09 },
      { minCopies: 100, perSheet36: 1.78 },
    ],
    confidence: 'high',
    notes: 'Smallest card.',
  },
  {
    group: 'deck',
    identity: 'HexDeck',
    displayName: 'Hex Deck',
    widthIn: 3.75,
    heightIn: 3.25,
    cardsPerSheet: 12,
    priceTiers: [
      { minCopies: 1, perSheet12: 3.0 },
      { minCopies: 100, perSheet12: 1.62 },
    ],
    confidence: 'high',
    notes: 'Hexagonal card.',
  },
  {
    group: 'deck',
    identity: 'CircleDeck',
    displayName: 'Circle Deck',
    widthIn: 3.5,
    heightIn: 3.5,
    cardsPerSheet: 12,
    priceTiers: [
      { minCopies: 1, perSheet12: 3.0 },
      { minCopies: 100, perSheet12: 1.62 },
    ],
    confidence: 'high',
    notes: 'Round card (3.5in dia).',
  },
  {
    group: 'deck',
    identity: 'DominoDeck',
    displayName: 'Domino Deck',
    widthIn: 1.75,
    heightIn: 3.5,
    cardsPerSheet: 24,
    priceTiers: [
      { minCopies: 1, perSheet24: 3.55 },
      { minCopies: 100, perSheet24: 1.98 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'DividerDeck',
    displayName: 'Divider Deck',
    widthIn: 3.0,
    heightIn: 3.5,
    cardsPerSheet: 15,
    priceTiers: [
      { minCopies: 1, perSheet15: 3.55 },
      { minCopies: 100, perSheet15: 1.7 },
    ],
    confidence: 'high',
    notes: 'Tabbed dividers.',
  },
  {
    group: 'deck',
    identity: 'BusinessDeck',
    displayName: 'Business Deck',
    widthIn: 2.0,
    heightIn: 3.5,
    cardsPerSheet: 21,
    priceTiers: [
      { minCopies: 1, perSheet21: 3.6 },
      { minCopies: 100, perSheet21: 1.9 },
    ],
    confidence: 'high',
    notes: 'Business-card sized.',
  },
  {
    group: 'deck',
    identity: 'CardCraftingDeck',
    displayName: 'Card Crafting Deck',
    widthIn: 2.66,
    heightIn: 4.7,
    cardsPerSheet: 10,
    priceTiers: [
      { minCopies: 1, perSheet10: 2.84 },
      { minCopies: 100, perSheet10: 1.55 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'ClearCardCraftingDeck',
    displayName: 'Clear Card Crafting Deck',
    widthIn: 2.66,
    heightIn: 4.7,
    cardsPerSheet: 10,
    priceTiers: [
      { minCopies: 1, perSheet10: 11.88 },
      { minCopies: 100, perSheet10: 5.91 },
    ],
    confidence: 'high',
    notes: 'Transparent stock; premium price.',
  },
  {
    group: 'deck',
    identity: 'ClearCardCraftingDeck',
    displayName: 'Clear Euro Poker Deck',
    widthIn: 2.48,
    heightIn: 3.46,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 11.88 },
      { minCopies: 100, perSheet18: 5.91 },
    ],
    confidence: 'medium',
    notes: 'Clear poker-size deck; verify identity/size param.',
  },
  {
    group: 'deck',
    identity: 'MintTinDeck',
    displayName: 'Mint Tin Deck',
    widthIn: 2.05,
    heightIn: 3.43,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 3.09 },
      { minCopies: 100, perSheet18: 1.78 },
    ],
    confidence: 'high',
    notes: 'Sized to fit Mint Tin.',
  },
  {
    group: 'deck',
    identity: 'USGameDeck',
    displayName: 'US Game Deck',
    widthIn: 2.2,
    heightIn: 3.43,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 3.09 },
      { minCopies: 100, perSheet18: 1.78 },
    ],
    confidence: 'high',
  },
  {
    group: 'deck',
    identity: 'TradingDeck',
    displayName: 'Trading Deck',
    widthIn: 2.5,
    heightIn: 3.5,
    cardsPerSheet: 18,
    priceTiers: [
      { minCopies: 1, perSheet18: 3.5 },
      { minCopies: 100, perSheet18: 1.85 },
    ],
    confidence: 'medium',
    notes: 'On storefront but not in dev-doc identity list; identity inferred.',
  },
];
