// @turnbased/engine-sdk
// Author-facing rule schemas, expressions, hooks, and helpers.

export const ENGINE_SDK_VERSION = '0.1.0';

export {
  compileRulebook,
  compileTriggerRules,
  compileTurnStructure,
  defineRulebook,
  evaluateScoringRules,
  evaluateWinConditions,
  materializeSetupRules,
  resolveRuleValue,
  resolveVisibilityDefaults,
} from './helpers';
export { createRuleHookRegistry } from './hooks';
export {
  evaluateRuleBooleanExpression,
  evaluateRuleExpression,
  evaluateRuleExpressionAst,
  evaluateRuleNumericExpression,
  parseRuleExpression,
} from './expressions';
export {
  declarativeActionTemplateSchema,
  declarativePhaseRuleSchema,
  declarativeStepRuleSchema,
  declarativeTriggerRuleSchema,
  rulebookSchema,
  ruleExpressionReferenceSchema,
  ruleHookReferenceSchema,
  rulePlayerSelectorSchema,
  ruleValueMapSchema,
  ruleValueTemplateSchema,
  scoringRuleSchema,
  setupRuleSchema,
  triggerControllerSelectorSchema,
  turnStructureRuleSchema,
  visibilityDefaultRuleSchema,
  visibilityRuleMatchSchema,
  winConditionRuleSchema,
} from './schemas';
export type {
  CompiledRulebookArtifacts,
  DeclarativeActionTemplate,
  DeclarativePhaseRule,
  DeclarativeStepRule,
  DeclarativeTriggerRule,
  RuleActionBuilderHook,
  RuleAffordancePolicyHook,
  RuleAIHintHook,
  RuleCompileOptions,
  RuleCompilationRuntime,
  RuleDerivedViewHook,
  RuleEvaluationRuntime,
  RuleExpressionReference,
  RuleHookContextBase,
  RuleHookReference,
  RuleHookRegistry,
  RuleHookRegistryInput,
  RulePlayerScope,
  RulePlayerSelector,
  RulePredicateHook,
  RulePrimitive,
  RuleScoringHook,
  RuleTargetGeneratorHook,
  RuleValueMap,
  RuleValueTemplate,
  RuleVisibilityHook,
  RulebookDefinition,
  ScoringEvaluationResult,
  ScoringRule,
  ScoringRuleEvaluation,
  ScoringRuleMode,
  SetupRule,
  SetupRuleEvaluation,
  TriggerControllerSelector,
  TriggerControllerScope,
  TurnStructureCompilation,
  TurnStructureRule,
  VisibilityDefaultRule,
  VisibilityEvaluationResult,
  VisibilityRuleApplication,
  VisibilityRuleMatch,
  VisibilityViewerScope,
  WinConditionEvaluation,
  WinConditionOutcome,
  WinConditionRule,
  RuleWinConditionHook,
  RuleWinConditionHookResult,
} from './types';
export type {
  RuleArrayNode,
  RuleBinaryNode,
  RuleExpressionBinaryOperator,
  RuleExpressionNode,
  RuleExpressionUnaryOperator,
  RuleIdentifierNode,
  RuleLiteralNode,
  RuleMemberNode,
  RuleUnaryNode,
} from './expressions';
