// @turnbased/engine-core
// Core game engine: reducer, state model, actions, events, triggers, turns, visibility, legal moves

export const ENGINE_VERSION = '0.1.0';

// State model
export * from './state';

// Action grammar
export {
  canonicalActionEventMap,
  canonicalActionSchema,
  getEventsForCanonicalAction,
  intentActionSchema,
  validateCanonicalAction,
  validateIntentAction,
} from './actions';
export {
  appendActionLog,
  createActionLogId,
  getNextPlayerIndex,
  hashGameState,
  nextRandomFloat,
  reduceGameState,
  replayCanonicalActions,
  serializeGameState,
  shuffleWithRandomState,
} from './reducer';
export {
  advanceTurnPhase,
  advanceTurnStep,
  clonePhaseDefinition,
  cloneStepDefinition,
  cloneTurnPhases,
  endTurn,
  insertTurnPhase,
  insertTurnStep,
  resetTurnStructure,
} from './turns';
export {
  applyActionWithTriggers,
  areAllPriorityParticipantsPassed,
  closePriorityWindow,
  createEventBus,
  createClosedPriorityWindow,
  createTriggerRegistry,
  currentPriorityPlayerHasDecision,
  emitDomainEvents,
  getPriorityOrder,
  getPriorityParticipants,
  openPriorityWindow,
  replayActionsWithTriggers,
  resolveStackWithTriggers,
} from './triggers';
export {
  canViewerSeeEntityDetails,
  canViewerSeeEntityPresence,
  canViewerSeeZoneContents,
  projectGameStateForAI,
  projectGameStateForPlayer,
  projectGameStateForViewer,
  resolveViewerContext,
} from './visibility';
export {
  generateLegalMoveTree,
  getValidDestinations,
  getValidEntitiesForDestination,
} from './legal-moves';
export type {
  ActionLogEntry,
  ActionSource,
  ActionSourceType,
  AddExtraTurnAction,
  AddResourceAction,
  AdvancePhaseAction,
  AdvanceStepAction,
  CanonicalAction,
  CanonicalActionTemplate,
  CanonicalActionType,
  ChooseOptionAction,
  CreateEntityAction,
  DecisionOptionPayload,
  DestroyEntityAction,
  DomainEventType,
  DrawFromZoneAction,
  EliminatePlayerAction,
  EndGameAction,
  EndTurnAction,
  HideEntityAction,
  InsertPhaseAction,
  InsertStepAction,
  IntentAction,
  IntentActionLoweringResult,
  MoveEntityAction,
  PassPriorityAction,
  PendingDecisionPayload,
  PhaseDefinitionPayload,
  PromptPlayerAction,
  QueueStackItemAction,
  RemoveResourceAction,
  ResolveStackItemAction,
  ReverseTurnOrderAction,
  RevealEntityAction,
  SetPropertyAction,
  SetScoreAction,
  ShuffleZoneAction,
  SkipTurnAction,
  StepDefinitionPayload,
  TransferControlAction,
} from './actions';
export type {
  DomainEvent,
  PriorityResponderContext,
  OptionalTriggerDecisionMetadata,
  RegisteredTrigger,
  TriggerDispatchResult,
  TriggerEngineOptions,
  TriggerExecutionContext,
  TriggerMatchContext,
  TriggerRegistration,
} from './triggers';
export type {
  FieldVisibilityRule,
  PlayerVisibleState,
  ResolvedViewerContext,
  SpectatorVisibilityPolicy,
  VisibilityFieldPolicies,
  VisibilityFieldPolicy,
  VisibilityProjectionOptions,
  VisibilityRedaction,
  ViewerContext,
  VisibleActionLogEntry,
  VisibleEntity,
  VisiblePendingDecision,
  VisibleStackItem,
  VisibleZone,
} from './visibility';
export type {
  CompiledLegalMoveTree,
  LegalAction,
  LegalActionBlueprint,
  LegalMoveDefinition,
  LegalMoveEngineContext,
  LegalMoveExecutionContext,
  LegalMoveExplanation,
  LegalMoveGenerationContext,
  LegalMoveGenerationHelpers,
  LegalMoveGenerationOptions,
  LegalMoveRequest,
  LegalMoveTree,
  LegalMoveValidationResult,
  LegalSubChoice,
  LegalSubChoiceOption,
  NormalizedLegalMoveRequest,
} from './legal-moves';
