import { Visibility } from '@turnbased/shared-types';
import { z } from 'zod';

import type { BuiltInComponentType } from './types';
import {
  countSchema,
  defaultContainerRenderHints,
  defaultCounterRenderHints,
  type ComponentManifestDefinition,
} from './catalog-helpers';

export const counterManifests: Pick<Record<BuiltInComponentType, ComponentManifestDefinition>, 'zone' | 'counter' | 'score-track' | 'text-box' | 'network'> = {
  zone: {
    type: 'zone',
    category: 'container',
    role: 'sub-component',
    displayName: 'Zone',
    description: 'A logical container for entities, collections, and local counters.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Zone'),
      maxCapacity: countSchema,
    }),
    defaultProperties: {
      label: 'Zone',
      maxCapacity: null,
    },
    renderHints: {
      surface: 'zone',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'open',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: ['board'],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: ['deck', 'hand', 'discard', 'bag', 'counter', 'track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: ['deck', 'hand', 'discard', 'bag', 'counter', 'track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'contents',
          label: 'Contents',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: ['deck', 'hand', 'discard', 'bag', 'counter', 'track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['area', 'logical-container'],
  },
  counter: {
    type: 'counter',
    category: 'counter',
    role: 'leaf',
    displayName: 'Counter',
    description: 'A numeric tracker for score, health, resources, or charges.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      value: { kind: 'number', label: 'Value' },
      min: { kind: 'number', label: 'Minimum' },
      max: { kind: 'number', label: 'Maximum' },
      step: { kind: 'number', label: 'Step' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Counter'),
      value: z.number().int().default(0),
      min: z.number().int().default(0),
      max: countSchema,
      step: z.number().int().positive().default(1),
    }),
    defaultProperties: {
      label: 'Counter',
      value: 0,
      min: 0,
      max: null,
      step: 1,
    },
    renderHints: {
      surface: 'counter',
      layout: 'freeform',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'increment',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantRoles: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['numeric', 'resource'],
  },
  'score-track': {
    type: 'score-track',
    category: 'counter',
    role: 'leaf',
    displayName: 'Score Track',
    description: 'A scoring component with ordered positions and marker occupancy.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      length: { kind: 'number', label: 'Length' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Score Track'),
      length: z.number().int().positive().default(20),
    }),
    defaultProperties: {
      label: 'Score Track',
      length: 20,
    },
    renderHints: {
      surface: 'counter',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantRoles: [],
      occupantTypes: ['token', 'piece'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: 1,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'markers',
          label: 'Score Markers',
          acceptsRoles: [],
          acceptsTypes: ['token', 'piece'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['score', 'progression'],
  },
  'text-box': {
    type: 'text-box',
    category: 'container',
    role: 'leaf',
    displayName: 'Text Box',
    description: 'A rich text annotation box for instructions, flavor, labels, and icon tokens on the board surface.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      contentHtml: { kind: 'string', label: 'Content HTML' },
      fontFamily: { kind: 'enum', label: 'Font Family', options: ['sans', 'serif', 'display', 'mono'] },
      fontSize: { kind: 'number', label: 'Font Size' },
      lineHeight: { kind: 'number', label: 'Line Height' },
      textColor: { kind: 'string', label: 'Text Color' },
      textAlign: { kind: 'enum', label: 'Text Align', options: ['left', 'center', 'right', 'justify'] },
      verticalAlign: { kind: 'enum', label: 'Vertical Align', options: ['start', 'center', 'end'] },
      padding: { kind: 'number', label: 'Padding' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Text Box'),
      contentHtml: z.string().default('<p>Text box</p>'),
      fontFamily: z.enum(['sans', 'serif', 'display', 'mono']).default('sans'),
      fontSize: z.number().min(10).max(96).default(22),
      lineHeight: z.number().min(1).max(2.4).default(1.4),
      textColor: z.string().default('#064e3b'),
      textAlign: z.enum(['left', 'center', 'right', 'justify']).default('left'),
      verticalAlign: z.enum(['start', 'center', 'end']).default('center'),
      padding: z.number().nonnegative().max(64).default(18),
    }),
    defaultProperties: {
      label: 'Text Box',
      contentHtml: '<p>Text box</p>',
      fontFamily: 'sans',
      fontSize: 22,
      lineHeight: 1.4,
      textColor: '#064e3b',
      textAlign: 'left',
      verticalAlign: 'center',
      padding: 18,
    },
    renderHints: {
      surface: 'board',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
      showLabel: false,
      showOccupancy: false,
      showCapacity: false,
      supportsCoordinates: false,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component', 'leaf'],
      allowedParentTypes: [],
      allowedChildRoles: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantRoles: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['annotation', 'text', 'board-ui'],
  },
  network: {
    type: 'network',
    category: 'container',
    role: 'sub-component',
    displayName: 'Network',
    description: 'A custom graph of connected nodes to construct arbitrary movement networks.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      nodes: { kind: 'json', label: 'Nodes Data' },
      edges: { kind: 'json', label: 'Edges Data' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Network'),
      nodes: z.any().default([]),
      edges: z.any().default([]),
    }),
    defaultProperties: {
      label: 'Network',
      nodes: [],
      edges: [],
    },
    renderHints: {
      surface: 'board',
      layout: 'graph',
      orientation: 'none',
      showLabel: true,
      showCount: false,
      showOccupancy: true,
      showOwnership: false,
      showCapacity: false,
      supportsCoordinates: true,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {},
    composition: {
      strategy: 'children',
      childSlots: [],
    },
    tags: ['container', 'network'],
  },
};
