import { Visibility } from '@turnbased/shared-types';
import { z } from 'zod';

import { createDefaultBoardAppearanceProperties } from './boardAppearance';
import type { BuiltInComponentType, ComponentManifest } from './types';
import { createRectangularGridCellCoordinates } from './gridCells';

const countSchema = z.number().int().nonnegative().nullable();
const boardSurfaceTextureIdSchema = z.enum(['none', 'felt', 'water', 'grass', 'wood', 'marble', 'leather', 'stone', 'sand', 'metal']);

const gridCellAppearancePropertyDefinitions = {
  cellBackground: { kind: 'string', label: 'Cell Background' },
  cellTextureId: { kind: 'enum', label: 'Cell Texture', options: boardSurfaceTextureIdSchema.options },
  cellTextureOpacity: { kind: 'number', label: 'Cell Texture Opacity' },
  cellBorderColor: { kind: 'string', label: 'Cell Border Color' },
  cellBorderWidth: { kind: 'number', label: 'Cell Border Width' },
  cellBorderRadius: { kind: 'number', label: 'Cell Border Radius' },
} as const;

function createGridCellAppearanceSchema(defaultBorderWidth: number, defaultBorderRadius: number) {
  return {
    cellBackground: z.string().trim().min(1).nullable().default(null),
    cellTextureId: boardSurfaceTextureIdSchema.default('none'),
    cellTextureOpacity: z.number().min(0).max(1).default(0.3),
    cellBorderColor: z.string().trim().min(1).nullable().default(null),
    cellBorderWidth: z.number().nonnegative().default(defaultBorderWidth),
    cellBorderRadius: z.number().nonnegative().default(defaultBorderRadius),
  };
}

function createGridCellAppearanceDefaults(defaultBorderWidth: number, defaultBorderRadius: number) {
  return {
    cellBackground: null,
    cellTextureId: 'none' as const,
    cellTextureOpacity: 0.3,
    cellBorderColor: null,
    cellBorderWidth: defaultBorderWidth,
    cellBorderRadius: defaultBorderRadius,
  };
}

const defaultContainerRenderHints = {
  showLabel: true,
  showCount: false,
  showOccupancy: true,
  showOwnership: false,
  showCapacity: true,
  supportsCoordinates: true,
} as const;

const defaultEntityRenderHints = {
  showLabel: true,
  showCount: false,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: false,
  supportsCoordinates: false,
} as const;

const defaultCollectionRenderHints = {
  showLabel: true,
  showCount: true,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: true,
  supportsCoordinates: false,
} as const;

const defaultCounterRenderHints = {
  showLabel: true,
  showCount: true,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: true,
  supportsCoordinates: false,
} as const;

const defaultBoardAppearance = createDefaultBoardAppearanceProperties();

const manifests: Record<BuiltInComponentType, ComponentManifest> = {
  board: {
    type: 'board',
    category: 'container',
    displayName: 'Board',
    description: 'A spatial root component that arranges spaces, tracks, and authored grid regions.',
    propertyDefinitions: {
      layout: { kind: 'enum', label: 'Layout', required: true, options: ['grid', 'hex', 'graph', 'custom'] },
      width: { kind: 'number', label: 'Width', description: 'Columns for grid boards.' },
      height: { kind: 'number', label: 'Height', description: 'Rows for grid boards.' },
      label: { kind: 'string', label: 'Label' },
      surfaceColor: { kind: 'string', label: 'Surface Color', description: 'Base background color for the board surface.' },
      surfaceTexture: {
        kind: 'enum',
        label: 'Surface Texture',
        description: 'Shared UI texture treatment for the board surface.',
        options: ['none', 'linen', 'felt', 'paper', 'crosshatch'],
      },
      surfaceBorderColor: { kind: 'string', label: 'Surface Border Color', description: 'Border color for the board surface.' },
      surfaceBorderWidth: { kind: 'number', label: 'Surface Border Width', description: 'Border thickness for the board surface.' },
      surfaceBorderStyle: {
        kind: 'enum',
        label: 'Surface Border Style',
        description: 'Border style for the board surface.',
        options: ['solid', 'dashed', 'dotted', 'double'],
      },
    },
    propertiesSchema: z.object({
      layout: z.enum(['grid', 'hex', 'graph', 'custom']),
      width: countSchema,
      height: countSchema,
      label: z.string().default('Board'),
      surfaceColor: z.string().default(defaultBoardAppearance.surfaceColor),
      surfaceTexture: z.enum(['none', 'felt', 'wood', 'marble', 'leather', 'stone', 'sand', 'metal', 'water', 'grass']).default(defaultBoardAppearance.surfaceTexture),
      surfaceTextureOpacity: z.number().min(0).max(1).default(defaultBoardAppearance.surfaceTextureOpacity),
      surfaceBorderColor: z.string().default(defaultBoardAppearance.surfaceBorderColor),
      surfaceBorderWidth: z.number().nonnegative().default(defaultBoardAppearance.surfaceBorderWidth),
      surfaceBorderStyle: z.enum(['solid', 'dashed', 'dotted', 'double']).default(defaultBoardAppearance.surfaceBorderStyle),
    }),
    defaultProperties: {
      layout: 'grid',
      width: null,
      height: null,
      label: 'Board',
      surfaceColor: defaultBoardAppearance.surfaceColor,
      surfaceTexture: defaultBoardAppearance.surfaceTexture,
      surfaceBorderColor: defaultBoardAppearance.surfaceBorderColor,
      surfaceBorderWidth: defaultBoardAppearance.surfaceBorderWidth,
      surfaceBorderStyle: defaultBoardAppearance.surfaceBorderStyle,
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: [],
      allowedParentTypes: [],
      allowedChildCategories: ['container', 'counter'],
      allowedChildTypes: ['space', 'track', 'text-box', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'resource-pile', 'counter', 'score-track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['container', 'counter'],
      occupantTypes: ['space', 'track', 'text-box', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'resource-pile', 'counter', 'score-track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'surface',
          label: 'Surface',
          acceptsCategories: ['container', 'counter'],
          acceptsTypes: ['space', 'track', 'text-box', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'resource-pile', 'counter', 'score-track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['spatial', 'surface', 'root'],
  },
  space: {
    type: 'space',
    category: 'container',
    displayName: 'Space',
    description: 'A single placeable location on a board or track.',
    propertyDefinitions: {
      x: { kind: 'number', label: 'X Coordinate' },
      y: { kind: 'number', label: 'Y Coordinate' },
      label: { kind: 'string', label: 'Label' },
      terrain: { kind: 'string', label: 'Terrain' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      x: z.number().int().default(0),
      y: z.number().int().default(0),
      label: z.string().default('Space'),
      terrain: z.string().default('plain'),
      maxCapacity: countSchema.default(null),
    }),
    defaultProperties: {
      x: 0,
      y: 0,
      label: 'Space',
      terrain: 'plain',
      maxCapacity: null,
    },
    renderHints: {
      surface: 'space',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'place',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'track', 'zone', 'hex-grid', 'square-grid', 'checkerboard-grid'],
      allowedChildCategories: ['entity', 'container'],
      allowedChildTypes: ['piece', 'token', 'resource-pile'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['entity', 'container'],
      occupantTypes: ['piece', 'token', 'resource-pile'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'occupant',
          label: 'Occupant',
          acceptsCategories: ['entity', 'container'],
          acceptsTypes: ['piece', 'token', 'resource-pile'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-space', 'occupancy'],
  },
  'hex-grid': {
    type: 'hex-grid',
    category: 'container',
    displayName: 'Hex Grid',
    description: 'A board-authored hex map region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit hex coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Hex Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(4, 5)),
      cellLabelPrefix: z.string().default('Hex'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(2, 0),
    }),
    defaultProperties: {
      label: 'Hex Grid',
      cells: createRectangularGridCellCoordinates(4, 5),
      cellLabelPrefix: 'Hex',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(2, 0),
    },
    renderHints: {
      surface: 'board',
      layout: 'hex',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: ['container'],
      allowedChildTypes: ['space'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['container'],
      occupantTypes: ['space'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsCategories: ['container'],
          acceptsTypes: ['space'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'hex', 'generated-spaces'],
  },
  'square-grid': {
    type: 'square-grid',
    category: 'container',
    displayName: 'Square Grid',
    description: 'A board-authored square grid region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit square-grid coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Square Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(6, 6)),
      cellLabelPrefix: z.string().default('Cell'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(1, 10),
    }),
    defaultProperties: {
      label: 'Square Grid',
      cells: createRectangularGridCellCoordinates(6, 6),
      cellLabelPrefix: 'Cell',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(1, 10),
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: ['container'],
      allowedChildTypes: ['space'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['container'],
      occupantTypes: ['space'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsCategories: ['container'],
          acceptsTypes: ['space'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'square', 'generated-spaces'],
  },
  'checkerboard-grid': {
    type: 'checkerboard-grid',
    category: 'container',
    displayName: 'Square Grid',
    description: 'A legacy square grid region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit square-grid coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Square Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(6, 6)),
      cellLabelPrefix: z.string().default('Cell'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(1, 10),
    }),
    defaultProperties: {
      label: 'Square Grid',
      cells: createRectangularGridCellCoordinates(6, 6),
      cellLabelPrefix: 'Cell',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(1, 10),
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: ['container'],
      allowedChildTypes: ['space'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['container'],
      occupantTypes: ['space'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsCategories: ['container'],
          acceptsTypes: ['space'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'square', 'legacy', 'generated-spaces'],
  },
  track: {
    type: 'track',
    category: 'container',
    displayName: 'Track',
    description: 'An ordered path of positions, suitable for movement and score progress.',
    propertyDefinitions: {
      layout: { kind: 'enum', label: 'Track Layout', required: true, options: ['linear', 'circular', 'branching'] },
      length: { kind: 'number', label: 'Length', required: true },
      label: { kind: 'string', label: 'Label' },
    },
    propertiesSchema: z.object({
      layout: z.enum(['linear', 'circular', 'branching']),
      length: z.number().int().positive().default(10),
      label: z.string().default('Track'),
    }),
    defaultProperties: {
      layout: 'linear',
      length: 10,
      label: 'Track',
    },
    renderHints: {
      surface: 'track',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: ['container', 'entity'],
      allowedChildTypes: ['space', 'resource-pile', 'piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantCategories: ['container', 'entity'],
      occupantTypes: ['space', 'resource-pile', 'piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'positions',
          label: 'Positions',
          acceptsCategories: ['container', 'entity'],
          acceptsTypes: ['space', 'resource-pile', 'piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['ordered', 'progression'],
  },
  'text-box': {
    type: 'text-box',
    category: 'container',
    displayName: 'Text Box',
    description: 'A rich text annotation box for instructions, flavor, labels, and icon tokens on the board surface.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      contentHtml: { kind: 'string', label: 'Content HTML' },
      fontFamily: { kind: 'enum', label: 'Font Family', options: ['sans', 'serif', 'display', 'mono'] },
      fontSize: { kind: 'number', label: 'Font Size' },
      lineHeight: { kind: 'number', label: 'Line Height' },
      textColor: { kind: 'string', label: 'Text Color' },
      textAlign: { kind: 'enum', label: 'Text Align', options: ['left', 'center', 'right', 'justify'] },
      verticalAlign: { kind: 'enum', label: 'Vertical Align', options: ['start', 'center', 'end'] },
      padding: { kind: 'number', label: 'Padding' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Text Box'),
      contentHtml: z.string().default('<p>Text box</p>'),
      fontFamily: z.enum(['sans', 'serif', 'display', 'mono']).default('sans'),
      fontSize: z.number().min(10).max(96).default(22),
      lineHeight: z.number().min(1).max(2.4).default(1.4),
      textColor: z.string().default('#064e3b'),
      textAlign: z.enum(['left', 'center', 'right', 'justify']).default('left'),
      verticalAlign: z.enum(['start', 'center', 'end']).default('center'),
      padding: z.number().nonnegative().max(64).default(18),
    }),
    defaultProperties: {
      label: 'Text Box',
      contentHtml: '<p>Text box</p>',
      fontFamily: 'sans',
      fontSize: 22,
      lineHeight: 1.4,
      textColor: '#064e3b',
      textAlign: 'left',
      verticalAlign: 'center',
      padding: 18,
    },
    renderHints: {
      surface: 'board',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
      showLabel: false,
      showOccupancy: false,
      showCapacity: false,
      supportsCoordinates: false,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['annotation', 'text', 'board-ui'],
  },
  zone: {
    type: 'zone',
    category: 'container',
    displayName: 'Zone',
    description: 'A logical container for entities, collections, and local counters.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
      isShared: { kind: 'boolean', label: 'Shared Zone' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Zone'),
      maxCapacity: countSchema,
      isShared: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Zone',
      maxCapacity: null,
      isShared: true,
    },
    renderHints: {
      surface: 'zone',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'open',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: ['collection', 'entity', 'counter', 'container'],
      allowedChildTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track', 'resource-pile'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['collection', 'entity', 'counter', 'container'],
      occupantTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track', 'resource-pile'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'contents',
          label: 'Contents',
          acceptsCategories: ['collection', 'entity', 'counter', 'container'],
          acceptsTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track', 'resource-pile'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['area', 'logical-container'],
  },
  'resource-pile': {
    type: 'resource-pile',
    category: 'container',
    displayName: 'Resource Pile',
    description: 'A permanent nested region that visually groups movable resources without making each resource part of the layout.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Resource Pile'),
      maxCapacity: countSchema,
    }),
    defaultProperties: {
      label: 'Resource Pile',
      maxCapacity: null,
    },
    renderHints: {
      surface: 'zone',
      layout: 'pile',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'open',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'space', 'track', 'zone'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'resources',
          label: 'Resources',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['resource', 'nested', 'inventory'],
  },
  deck: {
    type: 'deck',
    category: 'collection',
    displayName: 'Deck',
    description: 'An ordered, usually face-down collection that supports draw and shuffle actions.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      ordered: { kind: 'boolean', label: 'Ordered' },
      faceDown: { kind: 'boolean', label: 'Face Down by Default' },
      maxCards: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Deck'),
      ordered: z.boolean().default(true),
      faceDown: z.boolean().default(true),
      maxCards: countSchema,
    }),
    defaultProperties: {
      label: 'Deck',
      ordered: true,
      faceDown: true,
      maxCards: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'stack',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'draw',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Hidden,
      contentsVisibility: Visibility.Hidden,
      ownerPrivate: false,
      faceUpByDefault: false,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cards',
          label: 'Cards',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['ordered', 'draw'],
  },
  hand: {
    type: 'hand',
    category: 'collection',
    displayName: 'Hand',
    description: 'A player-owned private collection that presents items in a fan or row.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      fanDirection: { kind: 'enum', label: 'Fan Direction', options: ['left_to_right', 'right_to_left'] },
      maxCards: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Hand'),
      fanDirection: z.enum(['left_to_right', 'right_to_left']).default('left_to_right'),
      maxCards: countSchema,
    }),
    defaultProperties: {
      label: 'Hand',
      fanDirection: 'left_to_right',
      maxCards: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'fan',
      orientation: 'horizontal',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'multiple',
      primaryAction: 'select',
      dragEnabled: true,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Private,
      contentsVisibility: Visibility.Private,
      ownerPrivate: true,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'held-items',
          label: 'Held Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['player-area', 'private'],
  },
  discard: {
    type: 'discard',
    category: 'collection',
    displayName: 'Discard',
    description: 'A public pile of spent or resolved entities.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      faceUp: { kind: 'boolean', label: 'Face Up by Default' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Discard'),
      faceUp: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Discard',
      faceUp: true,
    },
    renderHints: {
      surface: 'collection',
      layout: 'pile',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'discarded-items',
          label: 'Discarded Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['history', 'public'],
  },
  bag: {
    type: 'bag',
    category: 'collection',
    displayName: 'Bag',
    description: 'A concealed random-access collection used for draws and pulls.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      randomDraw: { kind: 'boolean', label: 'Random Draw' },
      maxItems: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Bag'),
      randomDraw: z.boolean().default(true),
      maxItems: countSchema,
    }),
    defaultProperties: {
      label: 'Bag',
      randomDraw: true,
      maxItems: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'pile',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'draw',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Hidden,
      contentsVisibility: Visibility.Hidden,
      ownerPrivate: false,
      faceUpByDefault: false,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'contained-items',
          label: 'Contained Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['randomized', 'hidden'],
  },
  piece: {
    type: 'piece',
    category: 'entity',
    displayName: 'Piece',
    description: 'A movable actor or pawn that usually occupies spaces or tracks.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      moveStyle: { kind: 'string', label: 'Move Style' },
      size: { kind: 'enum', label: 'Size', options: ['small', 'medium', 'large'] },
      quantity: { kind: 'number', label: 'Quantity' },
      colorMode: { kind: 'enum', label: 'Color Mode', options: ['owner', 'neutral'] },
      supplyMode: { kind: 'enum', label: 'Supply Mode', options: ['finite', 'infinite'] },
    },
    propertiesSchema: z.object({
      label: z.string().default('Piece'),
      moveStyle: z.string().default('free'),
      size: z.enum(['small', 'medium', 'large']).default('medium'),
      quantity: z.number().int().positive().default(1),
      colorMode: z.enum(['owner', 'neutral']).default('owner'),
      supplyMode: z.enum(['finite', 'infinite']).default('finite'),
    }),
    defaultProperties: {
      label: 'Piece',
      moveStyle: 'free',
      size: 'medium',
      quantity: 1,
      colorMode: 'owner',
      supplyMode: 'finite',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container', 'collection', 'counter'],
      allowedParentTypes: ['space', 'zone', 'resource-pile', 'track', 'deck', 'hand', 'discard', 'bag', 'score-track'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['movable', 'occupant'],
  },
  token: {
    type: 'token',
    category: 'entity',
    displayName: 'Token',
    description: 'A lightweight marker for status, ownership, or track position.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      shape: { kind: 'enum', label: 'Shape', options: ['disc', 'cube', 'meeple'] },
      value: { kind: 'number', label: 'Value' },
      quantity: { kind: 'number', label: 'Quantity' },
      colorMode: { kind: 'enum', label: 'Color Mode', options: ['owner', 'neutral'] },
      supplyMode: { kind: 'enum', label: 'Supply Mode', options: ['finite', 'infinite'] },
    },
    propertiesSchema: z.object({
      label: z.string().default('Token'),
      shape: z.enum(['disc', 'cube', 'meeple']).default('disc'),
      value: z.number().int().nonnegative().default(1),
      quantity: z.number().int().positive().default(1),
      colorMode: z.enum(['owner', 'neutral']).default('owner'),
      supplyMode: z.enum(['finite', 'infinite']).default('finite'),
    }),
    defaultProperties: {
      label: 'Token',
      shape: 'disc',
      value: 1,
      quantity: 1,
      colorMode: 'owner',
      supplyMode: 'finite',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container', 'collection', 'counter'],
      allowedParentTypes: ['space', 'zone', 'resource-pile', 'track', 'deck', 'hand', 'discard', 'bag', 'score-track'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['marker', 'occupant'],
  },
  counter: {
    type: 'counter',
    category: 'counter',
    displayName: 'Counter',
    description: 'A numeric tracker for score, health, resources, or charges.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      value: { kind: 'number', label: 'Value' },
      min: { kind: 'number', label: 'Minimum' },
      max: { kind: 'number', label: 'Maximum' },
      step: { kind: 'number', label: 'Step' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Counter'),
      value: z.number().int().default(0),
      min: z.number().int().default(0),
      max: countSchema,
      step: z.number().int().positive().default(1),
    }),
    defaultProperties: {
      label: 'Counter',
      value: 0,
      min: 0,
      max: null,
      step: 1,
    },
    renderHints: {
      surface: 'counter',
      layout: 'freeform',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'increment',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['numeric', 'resource'],
  },
  'score-track': {
    type: 'score-track',
    category: 'counter',
    displayName: 'Score Track',
    description: 'A scoring component with ordered positions and marker occupancy.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      length: { kind: 'number', label: 'Length' },
      shared: { kind: 'boolean', label: 'Shared Track' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Score Track'),
      length: z.number().int().positive().default(20),
      shared: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Score Track',
      length: 20,
      shared: true,
    },
    renderHints: {
      surface: 'counter',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['token', 'piece'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['token', 'piece'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: 1,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'markers',
          label: 'Score Markers',
          acceptsCategories: ['entity'],
          acceptsTypes: ['token', 'piece'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['score', 'progression'],
  },
};

export const builtInComponentCatalog = manifests;
