import { Visibility } from '@turnbased/shared-types';
import { z } from 'zod';

import { createDefaultBoardAppearanceProperties } from './boardAppearance';
import { createRectangularGridCellCoordinates } from './gridCells';
import type { BuiltInComponentType } from './types';
import {
  countSchema,
  defaultContainerRenderHints,
  gridCellAppearancePropertyDefinitions,
  createGridCellAppearanceSchema,
  createGridCellAppearanceDefaults,
  type ComponentManifestDefinition,
} from './catalog-helpers';

const defaultBoardAppearance = createDefaultBoardAppearanceProperties();

export const spatialManifests: Pick<Record<BuiltInComponentType, ComponentManifestDefinition>, 'board' | 'tile' | 'space' | 'hex-grid' | 'square-grid' | 'checkerboard-grid' | 'track'> = {
  board: {
    type: 'board',
    category: 'container',
    role: 'top-level',
    displayName: 'Board',
    description: 'A spatial root component that arranges spaces, tracks, and authored grid regions.',
    propertyDefinitions: {
      physicalWidthMm: { kind: 'number', label: 'Width (mm)', description: 'Physical width in millimeters.' },
      physicalHeightMm: { kind: 'number', label: 'Height (mm)', description: 'Physical height in millimeters.' },
      catalogSlug: { kind: 'string', label: 'Catalog Product', description: 'Supplier catalog product slug.' },
      catalogVariantId: { kind: 'string', label: 'Catalog Variant', description: 'Supplier catalog variant ID.' },
      layout: { kind: 'enum', label: 'Layout', required: true, options: ['grid', 'hex', 'graph', 'custom'] },
      width: { kind: 'number', label: 'Width', description: 'Columns for grid boards.' },
      height: { kind: 'number', label: 'Height', description: 'Rows for grid boards.' },
      label: { kind: 'string', label: 'Label' },
      surfaceColor: { kind: 'string', label: 'Surface Color', description: 'Base background color for the board surface.' },
      surfaceTexture: {
        kind: 'enum',
        label: 'Surface Texture',
        description: 'Shared UI texture treatment for the board surface.',
        options: ['none', 'linen', 'felt', 'paper', 'crosshatch'],
      },
      surfaceBorderColor: { kind: 'string', label: 'Surface Border Color', description: 'Border color for the board surface.' },
      surfaceBorderWidth: { kind: 'number', label: 'Surface Border Width', description: 'Border thickness for the board surface.' },
      surfaceBorderStyle: {
        kind: 'enum',
        label: 'Surface Border Style',
        description: 'Border style for the board surface.',
        options: ['solid', 'dashed', 'dotted', 'double'],
      },
    },
    propertiesSchema: z.object({
      physicalWidthMm: z.number().positive().default(400),
      physicalHeightMm: z.number().positive().default(400),
      catalogSlug: z.string().default(''),
      catalogVariantId: z.string().default(''),
      layout: z.enum(['grid', 'hex', 'graph', 'custom']),
      width: countSchema,
      height: countSchema,
      label: z.string().default('Board'),
      surfaceColor: z.string().default(defaultBoardAppearance.surfaceColor),
      surfaceTexture: z.enum(['none', 'felt', 'wood', 'marble', 'leather', 'stone', 'sand', 'metal', 'water', 'grass']).default(defaultBoardAppearance.surfaceTexture),
      surfaceTextureOpacity: z.number().min(0).max(1).default(defaultBoardAppearance.surfaceTextureOpacity),
      surfaceBorderColor: z.string().default(defaultBoardAppearance.surfaceBorderColor),
      surfaceBorderWidth: z.number().nonnegative().default(defaultBoardAppearance.surfaceBorderWidth),
      surfaceBorderStyle: z.enum(['solid', 'dashed', 'dotted', 'double']).default(defaultBoardAppearance.surfaceBorderStyle),
    }),
    defaultProperties: {
      physicalWidthMm: 400,
      physicalHeightMm: 400,
      catalogSlug: '',
      catalogVariantId: '',
      layout: 'grid',
      width: null,
      height: null,
      label: 'Board',
      surfaceColor: defaultBoardAppearance.surfaceColor,
      surfaceTexture: defaultBoardAppearance.surfaceTexture,
      surfaceBorderColor: defaultBoardAppearance.surfaceBorderColor,
      surfaceBorderWidth: defaultBoardAppearance.surfaceBorderWidth,
      surfaceBorderStyle: defaultBoardAppearance.surfaceBorderStyle,
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: [],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'surface',
          label: 'Surface',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['spatial', 'surface', 'root'],
  },
  tile: {
    type: 'tile',
    category: 'container',
    role: 'top-level',
    displayName: 'Tile',
    description: 'A printable game tile with physical dimensions sourced from the supplier catalog.',
    propertyDefinitions: {
      physicalWidthMm: { kind: 'number', label: 'Width (mm)', description: 'Physical width in millimeters.' },
      physicalHeightMm: { kind: 'number', label: 'Height (mm)', description: 'Physical height in millimeters.' },
      shape: { kind: 'enum', label: 'Shape', description: 'The physical shape of the tile.', options: ['square', 'rectangle', 'circle', 'hexagon', 'triangle'] },
      label: { kind: 'string', label: 'Label' },
      catalogSlug: { kind: 'string', label: 'Catalog Product', description: 'Supplier catalog product slug.' },
      catalogVariantId: { kind: 'string', label: 'Catalog Variant', description: 'Supplier catalog variant ID.' },
      surfaceColor: { kind: 'string', label: 'Surface Color', description: 'Base background color for the tile surface.' },
      surfaceTexture: {
        kind: 'enum',
        label: 'Surface Texture',
        description: 'Shared UI texture treatment for the tile surface.',
        options: ['none', 'linen', 'felt', 'paper', 'crosshatch'],
      },
      surfaceBorderColor: { kind: 'string', label: 'Surface Border Color', description: 'Border color for the tile surface.' },
      surfaceBorderWidth: { kind: 'number', label: 'Surface Border Width', description: 'Border thickness for the tile surface.' },
      surfaceBorderStyle: {
        kind: 'enum',
        label: 'Surface Border Style',
        description: 'Border style for the tile surface.',
        options: ['solid', 'dashed', 'dotted', 'double'],
      },
    },
    propertiesSchema: z.object({
      physicalWidthMm: z.number().positive().default(100),
      physicalHeightMm: z.number().positive().default(100),
      shape: z.enum(['square', 'rectangle', 'circle', 'hexagon', 'triangle']).default('square'),
      label: z.string().default('Tile'),
      catalogSlug: z.string().default(''),
      catalogVariantId: z.string().default(''),
      surfaceColor: z.string().default(defaultBoardAppearance.surfaceColor),
      surfaceTexture: z.enum(['none', 'felt', 'wood', 'marble', 'leather', 'stone', 'sand', 'metal', 'water', 'grass']).default(defaultBoardAppearance.surfaceTexture),
      surfaceTextureOpacity: z.number().min(0).max(1).default(defaultBoardAppearance.surfaceTextureOpacity),
      surfaceBorderColor: z.string().default(defaultBoardAppearance.surfaceBorderColor),
      surfaceBorderWidth: z.number().nonnegative().default(defaultBoardAppearance.surfaceBorderWidth),
      surfaceBorderStyle: z.enum(['solid', 'dashed', 'dotted', 'double']).default(defaultBoardAppearance.surfaceBorderStyle),
    }),
    defaultProperties: {
      physicalWidthMm: 100,
      physicalHeightMm: 100,
      shape: 'square',
      label: 'Tile',
      catalogSlug: '',
      catalogVariantId: '',
      surfaceColor: defaultBoardAppearance.surfaceColor,
      surfaceTexture: defaultBoardAppearance.surfaceTexture,
      surfaceBorderColor: defaultBoardAppearance.surfaceBorderColor,
      surfaceBorderWidth: defaultBoardAppearance.surfaceBorderWidth,
      surfaceBorderStyle: defaultBoardAppearance.surfaceBorderStyle,
    },
    renderHints: {
      surface: 'board',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: [],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'surface',
          label: 'Surface',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: ['card', 'space', 'track', 'text-box', 'image-area', 'network', 'hex-grid', 'square-grid', 'checkerboard-grid', 'zone', 'counter', 'score-track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['spatial', 'surface', 'printable', 'tile'],
  },
  space: {
    type: 'space',
    category: 'container',
    role: 'sub-component',
    displayName: 'Space',
    description: 'A single placeable location on a board or track.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Space'),
      maxCapacity: countSchema.default(null),
    }),
    defaultProperties: {
      label: 'Space',
      maxCapacity: null,
    },
    renderHints: {
      surface: 'space',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'place',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'occupant',
          label: 'Occupant',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-space', 'occupancy'],
  },
  'hex-grid': {
    type: 'hex-grid',
    category: 'container',
    role: 'sub-component',
    displayName: 'Hex Grid',
    description: 'A board-authored hex map region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit hex coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Hex Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(4, 5)),
      cellLabelPrefix: z.string().default('Hex'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(2, 0),
    }),
    defaultProperties: {
      label: 'Hex Grid',
      cells: createRectangularGridCellCoordinates(4, 5),
      cellLabelPrefix: 'Hex',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(2, 0),
    },
    renderHints: {
      surface: 'board',
      layout: 'hex',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'hex', 'generated-spaces'],
  },
  'square-grid': {
    type: 'square-grid',
    category: 'container',
    role: 'sub-component',
    displayName: 'Square Grid',
    description: 'A board-authored square grid region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit square-grid coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Square Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(6, 6)),
      cellLabelPrefix: z.string().default('Cell'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(1, 10),
    }),
    defaultProperties: {
      label: 'Square Grid',
      cells: createRectangularGridCellCoordinates(6, 6),
      cellLabelPrefix: 'Cell',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(1, 10),
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'square', 'generated-spaces'],
  },
  'checkerboard-grid': {
    type: 'checkerboard-grid',
    category: 'container',
    role: 'sub-component',
    displayName: 'Square Grid',
    description: 'A legacy square grid region whose generated cells are individual spaces for engine play.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      cells: { kind: 'json', label: 'Cells', description: 'Explicit square-grid coordinates. Each coordinate becomes a generated space.' },
      cellLabelPrefix: { kind: 'string', label: 'Cell Label Prefix' },
      maxCapacity: { kind: 'number', label: 'Cell Capacity' },
      ...gridCellAppearancePropertyDefinitions,
    },
    propertiesSchema: z.object({
      label: z.string().default('Square Grid'),
      cells: z.array(z.object({
        x: z.number().int(),
        y: z.number().int(),
      })).default(createRectangularGridCellCoordinates(6, 6)),
      cellLabelPrefix: z.string().default('Cell'),
      maxCapacity: countSchema.default(null),
      ...createGridCellAppearanceSchema(1, 10),
    }),
    defaultProperties: {
      label: 'Square Grid',
      cells: createRectangularGridCellCoordinates(6, 6),
      cellLabelPrefix: 'Cell',
      maxCapacity: null,
      ...createGridCellAppearanceDefaults(1, 10),
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cells',
          label: 'Cells',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['board-grid', 'square', 'legacy', 'generated-spaces'],
  },
  track: {
    type: 'track',
    category: 'container',
    role: 'sub-component',
    displayName: 'Track',
    description: 'An ordered path of positions, suitable for movement and score progress.',
    propertyDefinitions: {
      layout: { kind: 'enum', label: 'Track Layout', required: true, options: ['linear', 'circular', 'branching'] },
      length: { kind: 'number', label: 'Length', required: true },
      label: { kind: 'string', label: 'Label' },
    },
    propertiesSchema: z.object({
      layout: z.enum(['linear', 'circular', 'branching']),
      length: z.number().int().positive().default(10),
      label: z.string().default('Track'),
    }),
    defaultProperties: {
      layout: 'linear',
      length: 10,
      label: 'Track',
    },
    renderHints: {
      surface: 'track',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'positions',
          label: 'Positions',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['ordered', 'progression'],
  },
};
