import { Visibility } from '@turnbased/shared-types';
import { z } from 'zod';

import type { BuiltInComponentType, ComponentManifest } from './types';

const countSchema = z.number().int().nonnegative().nullable();

const defaultContainerRenderHints = {
  showLabel: true,
  showCount: false,
  showOccupancy: true,
  showOwnership: false,
  showCapacity: true,
  supportsCoordinates: true,
} as const;

const defaultEntityRenderHints = {
  showLabel: true,
  showCount: false,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: false,
  supportsCoordinates: false,
} as const;

const defaultCollectionRenderHints = {
  showLabel: true,
  showCount: true,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: true,
  supportsCoordinates: false,
} as const;

const defaultCounterRenderHints = {
  showLabel: true,
  showCount: true,
  showOccupancy: false,
  showOwnership: true,
  showCapacity: true,
  supportsCoordinates: false,
} as const;

const manifests: Record<BuiltInComponentType, ComponentManifest> = {
  board: {
    type: 'board',
    category: 'container',
    displayName: 'Board',
    description: 'A spatial root component that arranges spaces, tracks, and zones.',
    propertyDefinitions: {
      layout: { kind: 'enum', label: 'Layout', required: true, options: ['grid', 'hex', 'graph', 'custom'] },
      width: { kind: 'number', label: 'Width', description: 'Columns for grid boards.' },
      height: { kind: 'number', label: 'Height', description: 'Rows for grid boards.' },
      label: { kind: 'string', label: 'Label' },
    },
    propertiesSchema: z.object({
      layout: z.enum(['grid', 'hex', 'graph', 'custom']),
      width: countSchema,
      height: countSchema,
      label: z.string().default('Board'),
    }),
    defaultProperties: {
      layout: 'grid',
      width: null,
      height: null,
      label: 'Board',
    },
    renderHints: {
      surface: 'board',
      layout: 'grid',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'select',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: [],
      allowedParentTypes: [],
      allowedChildCategories: ['container', 'counter'],
      allowedChildTypes: ['space', 'track', 'zone', 'counter', 'score-track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['container', 'counter'],
      occupantTypes: ['space', 'track', 'zone', 'counter', 'score-track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'surface',
          label: 'Surface',
          acceptsCategories: ['container', 'counter'],
          acceptsTypes: ['space', 'track', 'zone', 'counter', 'score-track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['spatial', 'surface', 'root'],
  },
  space: {
    type: 'space',
    category: 'container',
    displayName: 'Space',
    description: 'A single placeable location on a board or track.',
    propertyDefinitions: {
      x: { kind: 'number', label: 'X Coordinate' },
      y: { kind: 'number', label: 'Y Coordinate' },
      label: { kind: 'string', label: 'Label' },
      terrain: { kind: 'string', label: 'Terrain' },
    },
    propertiesSchema: z.object({
      x: z.number().int().default(0),
      y: z.number().int().default(0),
      label: z.string().default('Space'),
      terrain: z.string().default('plain'),
    }),
    defaultProperties: {
      x: 0,
      y: 0,
      label: 'Space',
      terrain: 'plain',
    },
    renderHints: {
      surface: 'space',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'place',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'track', 'zone'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: 1,
    },
    occupancyRules: {
      mode: 'single',
      capacity: 1,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: 1,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'occupant',
          label: 'Occupant',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: 1,
        },
      ],
    },
    tags: ['board-space', 'occupancy'],
  },
  track: {
    type: 'track',
    category: 'container',
    displayName: 'Track',
    description: 'An ordered path of positions, suitable for movement and score progress.',
    propertyDefinitions: {
      layout: { kind: 'enum', label: 'Track Layout', required: true, options: ['linear', 'circular', 'branching'] },
      length: { kind: 'number', label: 'Length', required: true },
      label: { kind: 'string', label: 'Label' },
    },
    propertiesSchema: z.object({
      layout: z.enum(['linear', 'circular', 'branching']),
      length: z.number().int().positive().default(10),
      label: z.string().default('Track'),
    }),
    defaultProperties: {
      layout: 'linear',
      length: 10,
      label: 'Track',
    },
    renderHints: {
      surface: 'track',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: ['container', 'entity'],
      allowedChildTypes: ['space', 'piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantCategories: ['container', 'entity'],
      occupantTypes: ['space', 'piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'positions',
          label: 'Positions',
          acceptsCategories: ['container', 'entity'],
          acceptsTypes: ['space', 'piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['ordered', 'progression'],
  },
  zone: {
    type: 'zone',
    category: 'container',
    displayName: 'Zone',
    description: 'A logical container for entities, collections, and local counters.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      maxCapacity: { kind: 'number', label: 'Capacity' },
      isShared: { kind: 'boolean', label: 'Shared Zone' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Zone'),
      maxCapacity: countSchema,
      isShared: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Zone',
      maxCapacity: null,
      isShared: true,
    },
    renderHints: {
      surface: 'zone',
      layout: 'freeform',
      orientation: 'none',
      ...defaultContainerRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'open',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board'],
      allowedChildCategories: ['collection', 'entity', 'counter', 'container'],
      allowedChildTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['collection', 'entity', 'counter', 'container'],
      occupantTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'contents',
          label: 'Contents',
          acceptsCategories: ['collection', 'entity', 'counter', 'container'],
          acceptsTypes: ['deck', 'hand', 'discard', 'bag', 'piece', 'token', 'counter', 'track'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['area', 'logical-container'],
  },
  deck: {
    type: 'deck',
    category: 'collection',
    displayName: 'Deck',
    description: 'An ordered, usually face-down collection that supports draw and shuffle actions.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      ordered: { kind: 'boolean', label: 'Ordered' },
      faceDown: { kind: 'boolean', label: 'Face Down by Default' },
      maxCards: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Deck'),
      ordered: z.boolean().default(true),
      faceDown: z.boolean().default(true),
      maxCards: countSchema,
    }),
    defaultProperties: {
      label: 'Deck',
      ordered: true,
      faceDown: true,
      maxCards: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'stack',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'draw',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Hidden,
      contentsVisibility: Visibility.Hidden,
      ownerPrivate: false,
      faceUpByDefault: false,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'cards',
          label: 'Cards',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['ordered', 'draw'],
  },
  hand: {
    type: 'hand',
    category: 'collection',
    displayName: 'Hand',
    description: 'A player-owned private collection that presents items in a fan or row.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      fanDirection: { kind: 'enum', label: 'Fan Direction', options: ['left_to_right', 'right_to_left'] },
      maxCards: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Hand'),
      fanDirection: z.enum(['left_to_right', 'right_to_left']).default('left_to_right'),
      maxCards: countSchema,
    }),
    defaultProperties: {
      label: 'Hand',
      fanDirection: 'left_to_right',
      maxCards: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'fan',
      orientation: 'horizontal',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'multiple',
      primaryAction: 'select',
      dragEnabled: true,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Private,
      contentsVisibility: Visibility.Private,
      ownerPrivate: true,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'held-items',
          label: 'Held Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['player-area', 'private'],
  },
  discard: {
    type: 'discard',
    category: 'collection',
    displayName: 'Discard',
    description: 'A public pile of spent or resolved entities.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      faceUp: { kind: 'boolean', label: 'Face Up by Default' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Discard'),
      faceUp: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Discard',
      faceUp: true,
    },
    renderHints: {
      surface: 'collection',
      layout: 'pile',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Public,
      contentsVisibility: Visibility.Public,
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'discarded-items',
          label: 'Discarded Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['history', 'public'],
  },
  bag: {
    type: 'bag',
    category: 'collection',
    displayName: 'Bag',
    description: 'A concealed random-access collection used for draws and pulls.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      randomDraw: { kind: 'boolean', label: 'Random Draw' },
      maxItems: { kind: 'number', label: 'Capacity' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Bag'),
      randomDraw: z.boolean().default(true),
      maxItems: countSchema,
    }),
    defaultProperties: {
      label: 'Bag',
      randomDraw: true,
      maxItems: null,
    },
    renderHints: {
      surface: 'collection',
      layout: 'pile',
      orientation: 'vertical',
      ...defaultCollectionRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'draw',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['zone', 'board'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['piece', 'token'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'stack',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['piece', 'token'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      zoneVisibility: Visibility.Hidden,
      contentsVisibility: Visibility.Hidden,
      ownerPrivate: false,
      faceUpByDefault: false,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'contained-items',
          label: 'Contained Items',
          acceptsCategories: ['entity'],
          acceptsTypes: ['piece', 'token'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['randomized', 'hidden'],
  },
  piece: {
    type: 'piece',
    category: 'entity',
    displayName: 'Piece',
    description: 'A movable actor or pawn that usually occupies spaces or tracks.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      moveStyle: { kind: 'string', label: 'Move Style' },
      size: { kind: 'enum', label: 'Size', options: ['small', 'medium', 'large'] },
    },
    propertiesSchema: z.object({
      label: z.string().default('Piece'),
      moveStyle: z.string().default('free'),
      size: z.enum(['small', 'medium', 'large']).default('medium'),
    }),
    defaultProperties: {
      label: 'Piece',
      moveStyle: 'free',
      size: 'medium',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container', 'collection', 'counter'],
      allowedParentTypes: ['space', 'zone', 'track', 'deck', 'hand', 'discard', 'bag', 'score-track'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['movable', 'occupant'],
  },
  token: {
    type: 'token',
    category: 'entity',
    displayName: 'Token',
    description: 'A lightweight marker for status, ownership, or track position.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      shape: { kind: 'enum', label: 'Shape', options: ['disc', 'cube', 'meeple'] },
      value: { kind: 'number', label: 'Value' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Token'),
      shape: z.enum(['disc', 'cube', 'meeple']).default('disc'),
      value: z.number().int().nonnegative().default(1),
    }),
    defaultProperties: {
      label: 'Token',
      shape: 'disc',
      value: 1,
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentCategories: ['container', 'collection', 'counter'],
      allowedParentTypes: ['space', 'zone', 'track', 'deck', 'hand', 'discard', 'bag', 'score-track'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['marker', 'occupant'],
  },
  counter: {
    type: 'counter',
    category: 'counter',
    displayName: 'Counter',
    description: 'A numeric tracker for score, health, resources, or charges.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      value: { kind: 'number', label: 'Value' },
      min: { kind: 'number', label: 'Minimum' },
      max: { kind: 'number', label: 'Maximum' },
      step: { kind: 'number', label: 'Step' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Counter'),
      value: z.number().int().default(0),
      min: z.number().int().default(0),
      max: countSchema,
      step: z.number().int().positive().default(1),
    }),
    defaultProperties: {
      label: 'Counter',
      value: 0,
      min: 0,
      max: null,
      step: 1,
    },
    renderHints: {
      surface: 'counter',
      layout: 'freeform',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'increment',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantCategories: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['numeric', 'resource'],
  },
  'score-track': {
    type: 'score-track',
    category: 'counter',
    displayName: 'Score Track',
    description: 'A scoring component with ordered positions and marker occupancy.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      length: { kind: 'number', label: 'Length' },
      shared: { kind: 'boolean', label: 'Shared Track' },
    },
    propertiesSchema: z.object({
      label: z.string().default('Score Track'),
      length: z.number().int().positive().default(20),
      shared: z.boolean().default(true),
    }),
    defaultProperties: {
      label: 'Score Track',
      length: 20,
      shared: true,
    },
    renderHints: {
      surface: 'counter',
      layout: 'linear',
      orientation: 'horizontal',
      ...defaultCounterRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: false,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentCategories: ['container'],
      allowedParentTypes: ['board', 'zone'],
      allowedChildCategories: ['entity'],
      allowedChildTypes: ['token', 'piece'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'track',
      capacity: null,
      occupantCategories: ['entity'],
      occupantTypes: ['token', 'piece'],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: 1,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'markers',
          label: 'Score Markers',
          acceptsCategories: ['entity'],
          acceptsTypes: ['token', 'piece'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['score', 'progression'],
  },
};

export const builtInComponentCatalog = manifests;
