import { z } from 'zod';

import type { BuiltInComponentType } from './types';
import {
  defaultEntityRenderHints,
  type ComponentManifestDefinition,
} from './catalog-helpers';

export const entityManifests: Pick<Record<BuiltInComponentType, ComponentManifestDefinition>, 'card' | 'piece' | 'token' | 'image-area'> = {
  card: {
    type: 'card',
    category: 'entity',
    role: 'sub-component',
    displayName: 'Card',
    description: 'A composable card face that can live in a deck, on a board, or inside another authored surface.',
    propertyDefinitions: {
      physicalWidthMm: { kind: 'number', label: 'Width (mm)', description: 'Physical width in millimeters.' },
      physicalHeightMm: { kind: 'number', label: 'Height (mm)', description: 'Physical height in millimeters.' },
      label: { kind: 'string', label: 'Label' },
      title: { kind: 'string', label: 'Title' },
      subtitle: { kind: 'string', label: 'Subtitle' },
    },
    propertiesSchema: z.object({
      physicalWidthMm: z.number().positive().default(63),
      physicalHeightMm: z.number().positive().default(88),
      label: z.string().default('Card'),
      title: z.string().default('Card Title'),
      subtitle: z.string().default('Card text'),
    }),
    defaultProperties: {
      physicalWidthMm: 63,
      physicalHeightMm: 88,
      label: 'Card',
      title: 'Card Title',
      subtitle: 'Card text',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'vertical',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: true,
      dropEnabled: true,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level'],
      allowedParentTypes: ['deck'],
      allowedChildRoles: ['top-level', 'sub-component', 'leaf'],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'multiple',
      capacity: null,
      occupantRoles: ['top-level', 'sub-component', 'leaf'],
      occupantTypes: [],
      allowMixedOccupants: true,
      allowSharedControl: true,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'face',
          label: 'Face',
          acceptsRoles: ['top-level', 'sub-component', 'leaf'],
          acceptsTypes: [],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['card', 'face', 'composable'],
  },
  piece: {
    type: 'piece',
    category: 'entity',
    role: 'top-level',
    displayName: 'Piece',
    description: 'A movable actor or pawn that functions as a structural root on the table.',
    propertyDefinitions: {
      physicalWidthMm: { kind: 'number', label: 'Width (mm)', description: 'Physical width in millimeters.' },
      physicalHeightMm: { kind: 'number', label: 'Height (mm)', description: 'Physical height in millimeters.' },
      label: { kind: 'string', label: 'Label' },
      shape: { kind: 'enum', label: 'Shape', options: ['circle', 'square', 'triangle', 'hexagon', 'meeple'] },
      backgroundColor: { kind: 'string', label: 'Background Color' },
      borderColor: { kind: 'string', label: 'Border Color' },
      borderWidth: { kind: 'number', label: 'Border Width' },
      size: { kind: 'enum', label: 'Size', options: ['small', 'medium', 'large'] },
      quantity: { kind: 'number', label: 'Quantity' },
      colorMode: { kind: 'enum', label: 'Color Mode', options: ['owner', 'neutral'] },
    },
    propertiesSchema: z.object({
      physicalWidthMm: z.number().positive().default(25),
      physicalHeightMm: z.number().positive().default(25),
      label: z.string().default('Piece'),
      shape: z.enum(['circle', 'square', 'triangle', 'hexagon', 'meeple']).default('circle'),
      backgroundColor: z.string().default('#10b981'),
      borderColor: z.string().default('rgba(6,78,59,0.7)'),
      borderWidth: z.number().nonnegative().default(2),
      size: z.enum(['small', 'medium', 'large']).default('medium'),
      quantity: z.number().int().positive().default(1),
      colorMode: z.enum(['owner', 'neutral']).default('owner'),
    }),
    defaultProperties: {
      physicalWidthMm: 25,
      physicalHeightMm: 25,
      label: 'Piece',
      shape: 'circle',
      backgroundColor: '#10b981',
      borderColor: 'rgba(6,78,59,0.7)',
      borderWidth: 2,
      size: 'medium',
      quantity: 1,
      colorMode: 'owner',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: [],
      allowedParentTypes: [],
      allowedChildRoles: ['leaf'],
      allowedChildTypes: ['image-area', 'text-box'],
      minChildren: 0,
      maxChildren: null,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantRoles: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'children',
      childSlots: [
        {
          id: 'face',
          label: 'Face',
          acceptsRoles: ['leaf'],
          acceptsTypes: ['image-area', 'text-box'],
          minChildren: 0,
          maxChildren: null,
        },
      ],
    },
    tags: ['movable', 'occupant'],
  },
  token: {
    type: 'token',
    category: 'entity',
    role: 'top-level',
    displayName: 'Token',
    description: 'A lightweight marker for status, ownership, or track position.',
    propertyDefinitions: {
      physicalWidthMm: { kind: 'number', label: 'Width (mm)', description: 'Physical width in millimeters.' },
      physicalHeightMm: { kind: 'number', label: 'Height (mm)', description: 'Physical height in millimeters.' },
      label: { kind: 'string', label: 'Label' },
      shape: { kind: 'enum', label: 'Shape', options: ['disc', 'cube', 'meeple'] },
      quantity: { kind: 'number', label: 'Quantity' },
      colorMode: { kind: 'enum', label: 'Color Mode', options: ['owner', 'neutral'] },
    },
    propertiesSchema: z.object({
      physicalWidthMm: z.number().positive().default(15),
      physicalHeightMm: z.number().positive().default(15),
      label: z.string().default('Token'),
      shape: z.enum(['disc', 'cube', 'meeple']).default('disc'),
      quantity: z.number().int().positive().default(1),
      colorMode: z.enum(['owner', 'neutral']).default('owner'),
    }),
    defaultProperties: {
      physicalWidthMm: 15,
      physicalHeightMm: 15,
      label: 'Token',
      shape: 'disc',
      quantity: 1,
      colorMode: 'owner',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      ...defaultEntityRenderHints,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'move',
      dragEnabled: true,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: true,
    },
    placementConstraints: {
      requiresParent: false,
      allowedParentRoles: [],
      allowedParentTypes: [],
      allowedChildRoles: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantRoles: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {
      ownerPrivate: false,
      faceUpByDefault: true,
    },
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['marker', 'occupant'],
  },
  'image-area': {
    type: 'image-area',
    category: 'entity',
    role: 'leaf',
    displayName: 'Image Area',
    description: 'An image annotation meant for decorating the board surface.',
    propertyDefinitions: {
      label: { kind: 'string', label: 'Label' },
      imageUrl: { kind: 'string', label: 'Image URL', required: true },
      opacity: { kind: 'number', label: 'Opacity' },
      objectFit: { kind: 'enum', label: 'Object Fit', options: ['cover', 'contain', 'fill'] },
    },
    propertiesSchema: z.object({
      label: z.string().default('Image'),
      imageUrl: z.string().default(''),
      opacity: z.number().min(0).max(1).default(1),
      objectFit: z.enum(['cover', 'contain', 'fill']).default('contain'),
    }),
    defaultProperties: {
      label: 'Image',
      imageUrl: '',
      opacity: 1,
      objectFit: 'contain',
    },
    renderHints: {
      surface: 'entity',
      layout: 'freeform',
      orientation: 'none',
      showLabel: false,
      showCount: false,
      showOccupancy: false,
      showOwnership: false,
      showCapacity: false,
      supportsCoordinates: false,
    },
    interactionDefaults: {
      selectionMode: 'single',
      primaryAction: 'inspect',
      dragEnabled: false,
      dropEnabled: false,
      keyboardNavigable: true,
      highlightValidDestinations: false,
    },
    placementConstraints: {
      requiresParent: true,
      allowedParentRoles: ['top-level', 'sub-component'],
      allowedParentTypes: [],
      allowedChildRoles: [],
      allowedChildTypes: [],
      minChildren: 0,
      maxChildren: 0,
    },
    occupancyRules: {
      mode: 'none',
      capacity: 0,
      occupantRoles: [],
      occupantTypes: [],
      allowMixedOccupants: false,
      allowSharedControl: false,
      perPlayerLimit: null,
    },
    visibilityDefaults: {},
    composition: {
      strategy: 'leaf',
      childSlots: [],
    },
    tags: ['annotation', 'visual'],
  },
};
