// @turnbased/engine-components
// Built-in placeable game components, schemas, and composition helpers.

export const COMPONENTS_VERSION = '0.2.0';

export { builtInComponentCatalog } from './catalog';
export {
  BOARD_BORDER_STYLE_OPTIONS,
  BOARD_SURFACE_TEXTURE_OPTIONS,
  createDefaultBoardAppearanceProperties,
  resolveBoardAppearanceProperties,
} from './boardAppearance';
export {
  getBoardComponentPreset,
  listBoardComponentPresets,
} from './boardPresets';
export {
  createRectangularGridCellCoordinates,
  getGridCellLabel,
  getGridCoordinateKey,
  listGridNeighborOptions,
  normalizeGridCellCoordinates,
  readGridCellCoordinates,
  readGridCellStyle,
} from './gridCells';
export {
  builtInCatalog,
  createComponentCatalog,
  createComponentInstance,
  getBuiltInComponentManifest,
  listAuthorableBuiltInComponents,
  listBuiltInComponents,
  validateComponentOccupancy,
  validateComponentPlacement,
  validateComponentTree,
} from './helpers';
export {
  builtInComponentTypeSchema,
  componentAuthoringDiscoverabilitySchema,
  componentAuthoringMetadataSchema,
  componentBindingsSchema,
  componentCategorySchema,
  componentCompositionSchema,
  componentFrameSchema,
  componentInstanceSchema,
  componentInteractionDefaultsSchema,
  componentLayoutSchema,
  componentManifestSchema,
  componentOccupancyModeSchema,
  componentOccupancyRulesSchema,
  componentOrientationSchema,
  componentPlacementConstraintsSchema,
  componentPlacementSchema,
  componentPrimaryActionSchema,
  componentPropertyDefinitionSchema,
  componentPropertyKindSchema,
  componentRenderHintsSchema,
  componentSelectionModeSchema,
  componentSlotDefinitionSchema,
  componentSurfaceSchema,
  componentVisibilityDefaultsSchema,
  structuralRoleSchema,
} from './schemas';
export type {
  BoardAppearanceProperties,
  BoardBorderStyle,
  BoardComponentPreset,
  BoardComponentPresetFamily,
  BoardSurfaceTextureId,
  BuiltInComponentType,
  ComponentBindings,
  ComponentCatalog,
  ComponentCategory,
  ComponentComposition,
  ComponentCompositionStrategy,
  ComponentAuthoringDiscoverability,
  ComponentAuthoringMetadata,
  ComponentFrame,
  ComponentInstanceModel,
  ComponentInteractionDefaults,
  ComponentLayout,
  ComponentManifest,
  ComponentOccupancyMode,
  ComponentOccupancyRules,
  ComponentOrientation,
  ComponentPlacement,
  ComponentPlacementConstraints,
  ComponentPrimaryAction,
  ComponentPropertyDefinition,
  ComponentPropertyKind,
  ComponentRenderHints,
  ComponentSelectionMode,
  ComponentSlotDefinition,
  ComponentSurface,
  ComponentValidationIssue,
  ComponentValidationResult,
  ComponentVisibilityDefaults,
  CreateComponentInstanceOptions,
  GridCellCoordinate,
  GridCellStyle,
  OccupancyValidationContext,
  StructuralRole,
} from './types';
